### ISSUE TITLE
ClassicThemeRestorer will not update in Firefox 56.0.2 and is broken

### ISSUE THREAD

**Issue by Wskyy** [Aris-t2/ClassicThemeRestorer#407] opened 2019-05-08 16:36 UTC
As a result of the signature problem at Firefox ClassicThemeRestorer will no longer work in Firefox 56.0.2 yet other extensions do work such as Status-4-Evar and HTTPSEverywhere.  The latter worked after an update, the former was never disabled which could offer some clues.
I tried the suggested links https://github.com/Aris-t2/ClassicThemeRestorer/releases/tag/1.7.7.3 or https://github.com/Aris-t2/ClassicThemeRestorer/releases/ and the xpi does not appear for 1.7.7.3.  I tried installing 1.7.7.2 and Firefox reports it as corrupt.
I was able to install 1.7.8 on a portable version of the developer version of firefox 56.0.b2

**Comment by Aris-t2** [comment] 2019-05-09 07:11
The problem is, that devs can not sign add-ons. This was always done by Mozillas AMO server when posting a new version online. Since old add-ons can not be uploaded to AMO anymore, there is nothing I can do about this issue.

There was a "hotfix" xpi file from Mozilla, but it does not work on all Fx versions. Not sure, if it will on Fx52-56: https://storage.googleapis.com/moz-fx-normandy-prod-addons/extensions/hotfix-update-xpi-intermediate%40mozilla.com-1.0.2-signed.xpi

**Comment by Aris-t2** [comment] 2019-05-10 08:53
Sound like Mozilla might "fix" this issue for older Fx versions too. (No ETA yet)

https://www.ghacks.net/2019/05/09/mozilla-will-fix-add-on-signing-issue-for-older-firefox-versions/

**Comment by sharov-am** [comment] 2019-05-13 10:44
Hi.

I turned of xpinstall.signatures.required  but still I'm unable to  install ClassicThemeRestorer  1.7.7.2 for 56.0.2.  I got "...corrupted" message. Why is that?

**Comment by Aris-t2** [comment] 2019-05-13 11:55
Probably, because the "expired certificate" bug is not yet fixed on Fx 56. Not sure this will every happen, but there is nothing I can do about. There is no way to sign old add-ons anymore.

**Comment by Aris-t2** [comment] 2019-05-13 11:56
Here is a fix:

https://www.reddit.com/r/firefox/comments/bkspmk/addons_fix_for_5602_older/

**Comment by Aris-t2** [comment] 2019-05-14 05:19
Official fix from Mozilla:
https://addons.mozilla.org/en-US/firefox/addon/disabled-add-on-fix-52-56/

**Comment by Wskyy** [comment] 2019-05-14 06:30
Thank you for your diligence!  I already tried the prior one
https://www.reddit.com/r/firefox/comments/bkspmk/addons_fix_for_5602_older/
and it worked great but the official one might be more secure.  Will
keep these links.
Thanks again.

**Closed** 2019-08-06 12:11 UTC
Labels: bug, fixed
