### ISSUE TITLE
'Web Developer' add-ons toolbar uses toolbar appearance based on mode tag

### ISSUE THREAD

**Issue by thany** [Aris-t2/ClassicThemeRestorer#246] opened 2016-07-29 20:02 UTC
This addon causes Web Developer toolbar to have its icons ABOVE the text. This wasn't so until a few days ago. Disabling this addon proves that I'm right: then the buttons look normal again - icons and text horizontally.

Yes, I've uninstalled and reinstalled said toolbar, to no avail. The bug is in Classic Theme Restorer, clearly.

This is what it looks like with CTR installed:
![1](https://cloud.githubusercontent.com/assets/152227/17261903/8873a87c-55d8-11e6-8a70-aa134a076a60.PNG)

And this is what it's supposed to look like:
![2](https://cloud.githubusercontent.com/assets/152227/17261910/902638d2-55d8-11e6-98d8-f7d63c968a48.PNG)

So the dropdown arrows have been trashed as well.

This happens with a CLEAN installation in a CLEAN profile with NO settings made to either addon, nor to Firefox, whatsoever.

**Comment by Aris-t2** [comment] 2016-07-29 22:25
You are only partly right.

CTR has added support for old toolbar modes by default. This means code like toolbarname[mode=full] or toolbarname[mode=text] now get applied correctly, if the add-on sets them (like in Fx 28 for example).

The "bug" you are accusing CTR off is in fact not a bug, but what "Web Developer" developer initially had in mind and maybe forgot to remove after updating his add-on to Firefox 29+. If you want this to be removed, you have to ask "Web Developer" developer to remove the mode tag you see on the screen shot.

![1](https://cloud.githubusercontent.com/assets/6013569/17265073/1edb13dc-55ec-11e6-91e6-a93796b3b693.png)

**Comment by Aris-t2** [comment] 2016-07-29 23:46
Looks like this behavior is really intended by "Web Developer" developer. I will exclude that toolbar from CTRs code on next beta/release.

**Comment by thany** [comment] 2016-07-30 21:52
But, without CTR the toolbar looks fine. And to my knowledge the WDT has never ever looked that way. And I've been using it literally for as long as it has existed (and Firefox since before it was called Firefox ;))

**Comment by Aris-t2** [comment] 2016-07-30 22:24
The toolbar[mode="full"] appearance of the Web Developer toolbar will be fixed on next beta/release.

**Closed** 2016-08-05 13:38 UTC
Labels: bug
