### ISSUE TITLE
Double click tab bar opens 2 tabs

### ISSUE THREAD

**Issue by q1k** [Aris-t2/ClassicThemeRestorer#239] opened 2016-07-14 18:36 UTC
For some reason having 'Double click on toolbar opens a new tab' checked, will make double clicking the empty tab bar area to open 2 tabs, not just one. BTW, I have "tabs not on top v1" selected.

**Comment by Aris-t2** [comment] 2016-07-14 19:36
You are not the first one reporting this, but in most cases another tab add-on like TabMixPlus, TabUtilities or Tabkit (or even a user script) is responsible for this. Do you have one of them installed?

Check a new browser profile with only CTR installed. If nothing helps, disable CTR option to open a new tab, and use the one provided by whatever is causing it. ;-)

I'm not sure, if I already asked you before, what OS are you using?

**Comment by q1k** [comment] 2016-07-14 21:50
Nope, I have none of those installed, I have no other addons interfering with the toolbars behavior.

**Comment by Aris-t2** [comment] 2016-07-15 10:47
The default browser preference **browser.tabs.drawInTitlebar** (CTR offers only a switch for it) is responsible for the "double click to open a new tab" feature. I will tweak the code to exclude it from being enabled when OS titlebar is active.

Disabling or removing CTR does not revert the changes you have done to browsers default preferences by hitting their switches (checkboxes). This is not a bug, this is done on purpose. Browsers default preferences are additionally "visible" on CTR prefswindow below their corresponding switches (about:config >> name.of.preference).

**Comment by q1k** [comment] 2016-07-15 22:39
OK, thanks for the info.

**Comment by Aris-t2** [comment] 2016-07-16 07:23
Thanks for finding the exact case on how and when it happens. Now I was finally able to fix this.

**Comment by jonathanmcdougall** [comment] 2016-08-03 02:38
Funnily enough, double-clicking on the tab bar recently stopped working at all for me. The only way I can make it work is by enabling `drawInTitlebar`, which I don't want to do. I also noticed that the "Double click on toolbar opens a new tab" option is now disabled and checked (and `dblclnewtab` is true), but it doesn't seem to be used at all. I'm not sure what happened to the other guy, but now that feature is completely broken for me.

**Comment by jonathanmcdougall** [comment] 2016-08-03 03:40
I've been digging a bit more into the  [1.5.5beta4](https://github.com/Aris-t2/ClassicThemeRestorer/commit/4ed9c82fd49c1141c8ce04a4df6a5496112e12ae) checkin. You said that 

> The default browser preference browser.tabs.drawInTitlebar [..] is responsible for the "double click to open a new tab" feature

Are you sure about that? If I start with `-safe-mode`, toggling that setting doesn't do anything about double-clicking for a new tab. That feature seems to have been removed completely when tabs in titlebar became a thing.

I tried changing `overlay.js` to remove the check, but this new extension signing thing is a pain, so I can't do it tonight.

**Comment by Aris-t2** [comment] 2016-08-03 10:06
Which Windows version are you using? I tested this on Windows XP, 7, 8 and 10.

Please test a new Firefox profile without any add-ons installed (not even CTR).
On first Firefox start double click on tabs toolbar and you will see the window maximizes/minimizes.
Now go to "Customizing mode", hit the "Title Bar" button and leave "Customizing mode".
You will see double clicks on tabs toolbar are now opening new tabs.
Because of that CTRs "double click" option gets disabled once CTRs detects OS titlebar.

I have not tested any other tab add-ons, that might interfere with this.

**Comment by jonathanmcdougall** [comment] 2016-08-04 00:08
This is on Windows 10. A new profile does in fact work correctly, as does my current profile with all addons disabled. I have no idea what I did wrong last night, sorry for the scare. In fact, it seems to be a problem with a [recent update to Tree Style Tab](https://github.com/piroor/treestyletab/issues/1108). Adding the following in `userChrome.css` fixes it, although I think it introduces other problems with scrolling:

    #navigator-toolbox > #TabsToolbar
    {
        -moz-binding: url("chrome://global/content/bindings/toolbar.xml#toolbar")!important;
    }

You may close this again.

**Comment by Aris-t2** [comment] 2016-08-04 08:24
Good to know you found the culpit. Maybe TST dev should be notified about this too?

**Closed by Aris-t2** 2016-08-04 08:24 UTC
Labels: bug
