### ISSUE TITLE
[Lin] CTR conflict with LastPass 

### ISSUE THREAD

**Issue by Zack-od-Bins** [Aris-t2/ClassicThemeRestorer#358] opened 2017-08-05 14:58 UTC
Hi, I'm using Firefox 52.0.2 (64-bits) with CTR version 1.6.8.1 and LastPass 4.1.54 on an Ubuntu (64-bits) based PC (Linux Mint XFCE). 

Since yesterday the LastPass icon is missing. There also is no LastPass icon in the menu with the additional icons to adjust the interface with. According to 'Recent updates' in the add-on manager, CTR was updated more recently then LastPass. 

I tried reinstalling CTR and reinstalling LastPass, but no success. When I disable CTR, the icon is restored to the FF interface. I do not know if the problem lies with LastPass or CTR. I'm attaching my settings. Hopefully someone can find a solution, or advise me in the case I am making a mistake in my settings. 

Regards,

[CTRpreferences.txt](https://github.com/Aris-t2/ClassicThemeRestorer/files/1202440/CTRpreferences.txt)

[CTRpreferences.json.zip](https://github.com/Aris-t2/ClassicThemeRestorer/files/1202441/CTRpreferences.json.zip)

**Comment by Aris-t2** [comment] 2017-08-05 16:14
This might be the issue, where LastPass always tries to add its button to navigation toolbars end, but because it is not a "default" toolbar button (it ignores all default toolbar classes) it vanishes. Try to enable default toolbar buttons instead of small buttons to see, if the issue can be solved that way.

I ran some tests and LastPass button did not vanish using your settings with Firefox 50.0.2/52.2.1ESR.

Maybe a new browser profile for testing with only LastPass and CTR installed might solve the issue. Backup you current profile first (Home//.mozilla/).

**Comment by Aris-t2** [comment] 2017-08-29 03:47
Since there was not further answer whether this bug is fixed by creating a new profile or not and mainly because I still can not reproduce this atm, I'm closing this bug.

**Closed by Aris-t2** 2017-08-29 03:47 UTC
